// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwfyryvnlomqtylwwmxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3ZnlyeXZubG9tcXR5bHd3bXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjU1ODIsImV4cCI6MjA2NjMwMTU4Mn0.Bp7RgaKvN_QGlIHIgx4-lU4rN8lKFm5M6f6CVnVnbRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);